VM_NAME = 'boreale-macos'
VM_USER = 'vagrant'

Vagrant.configure(2) do |config|
  config.vm.box = 'ashiq/osx-10.14'

  config.vm.hostname = VM_NAME
  config.vm.provider "virtualbox" do |v|
    v.name = VM_NAME
    v.memory = 2048
  end

  # config.vm.network "private_network", type: "dhcp"
  # config.vm.synced_folder "../../.", "/Users/vagrant/boreale-macos/", type: "nfs"
  config.vm.synced_folder "../../.", "/Users/vagrant/boreale-macos/", type: "rsync", owner: "vagrant", group: "wheel"
  # config.vm.synced_folder ".", "/vagrant", type: "nfs"

    # setup script
    config.vm.provision "shell", privileged: false, inline: <<-SHELL
      brew install \
        coreutils automake autoconf openssl \
        libyaml readline libxslt libtool unixodbc \
        unzip curl

      git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.7.1
      echo -e '\n. $HOME/.asdf/asdf.sh' >> ~/.bash_profile
      echo -e '\n. $HOME/.asdf/completions/asdf.bash' >> ~/.bash_profile

      $HOME/.asdf/bin/asdf plugin-add erlang
      $HOME/.asdf/bin/asdf install erlang 21.0 https://github.com/asdf-vm/asdf-erlang.git
      $HOME/.asdf/bin/asdf global erlang 21.0

      $HOME/.asdf/bin/asdf plugin-add elixir
      $HOME/.asdf/bin/asdf install elixir 1.8.1-otp-21 https://github.com/asdf-vm/asdf-elixir.git
      $HOME/.asdf/bin/asdf global elixir 1.8.1-otp-21

    SHELL

    # startup script
    config.vm.provision "shell", privileged: false, run: 'always', inline: <<-SHELL
      cd boreale-macos/
      mix local.rebar --force
      mix local.hex --force
      mix deps.get
      mix deps.compile
      mix compile
      MIX_ENV=macos mix release
  SHELL
end
